crednet/expense-package

- src/Http/Controllers/Admin/TripsController.php
This PR is created to fix wrong controller namespace
CI not passing.
> fix(namespace): fix namespace path

- src/Http/Controllers/TransferController.php
- src/Services/TransferService.php
> bug(transfer): fix transfer

- src/Http/Controllers/TransferController.php
- src/Services/ExpenseProcess.php
> chore(payment-service): debugging payment service

- src/Http/Controllers/TransferController.php
- src/Http/Requests/TransferRequest.php
- src/Services/ExpenseProcess.php
- src/Services/TransferService.php
- src/routes/api.php
> fix(expense-refactor): fix transfer through cash wallet

- src/Services/ExpenseProcess.php
> fix(cash-reversal) cash reversal

- src/Http/Controllers/TripsController.php
- src/Services/ExpenseProcess.php
- src/Services/TripsService.php
- src/routes/api.php
- [*] The commit message follows our guidelines
- [] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been added / updated (for bug fixes / features)
- [*] Bugfix
- [*] Refactoring (no functional changes, no api changes)
Update trips side of the expense package
> update trips package

- src/Config/expense.php
- src/routes/api.php
> fix(hot-fix-middleware): add middleware to route file

- src/Config/expense.php
- src/Database/migrations/create_trip_travellers_table.stub
- src/Database/migrations/create_trips_table.stub
- src/ExpenseServiceProvider.php
- src/Http/Controllers/Admin/TripsController.php
- src/Models/Trip.php
- src/Models/TripsBookingDetails.php
- src/Models/TripsTraveller.php
- src/Services/ExpenseProcess.php
- src/Services/TripsService.php
- src/routes/api.php
> fix(trips): minor adjustments and addition of migration files for trips

- src/Database/migrations/create_trips_travellers_table.stub
- src/Models/Trip.php
- src/Models/TripTraveller.php
- src/Services/TripsService.php
> fix(trips): fix error in flight booking

- src/Services/TripsService.php
> fix(fix): update

- src/Services/TripsService.php
> fix(trips): changes to trips

- src/Services/TripsService.php
> fix(trips): update trips travellers

- src/Services/DuplicateTransactionService.php
> chore: add `userId` parameter to avoid tight coupling

- src/Models/Trip.php
- src/Services/TripsService.php
- src/routes/api.php
> fix(trips): move trips to corporate loans

- src/Contract/ExpenseContract.php
- src/Facades/Expense.php
- src/Services/Bills/BaxiService.php
- src/Services/DuplicateTransactionService.php
- src/Services/ExpenseProcess.php
> fix(bills): no refund on electricity request

- src/Contract/ExpenseContract.php
- src/Facades/Expense.php
- src/Services/DuplicateTransactionService.php
- src/Services/ExpenseProcess.php
- src/Traits/TransferTrait.php
> bills and transfer fixes - disable immediate refund

- src/Services/Bills/BaxiService.php
- src/Traits/BIllTransactionTrait.php
> add update bill transaction method to bills transaction trait

- src/Utilities/helpers.php
> chore: add `statusCode` to response structure

- src/Services/ExpenseProcess.php
- src/Utilities/helpers.php
> return array in reverseCash method

- src/Config/expense.php
- src/routes/api.php
> add daily transfer counts and maximum cash transfers middlewares

- src/Models/Trip.php
> update trips column type

- src/routes/api.php
> update develop branch

- src/Models/Trip.php
- src/routes/api.php
> update trips model

- .github/workflows/laravel.yml
> chore: add dev branch to CI

- src/Http/Controllers/TransferController.php
- src/Http/Requests/TransferRequest.php
- src/Services/ExpenseProcess.php
- src/Services/TransferService.php
- src/Traits/BIllTransactionTrait.php
- src/Utilities/helpers.php
> chore: requests making improvement

- src/Http/Controllers/TransferController.php
> chore: fix regression

- src/Config/expense.php
- src/routes/api.php
> remove pnd middleware
